// Regenerates src/icons.ts from every PNG in icons/.
// Run with: yarn icons

import { readdirSync, readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import path from 'node:path'

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const iconsDir = path.join(rootDir, 'icons')
const outFile = path.join(rootDir, 'src', 'icons.ts')

// Source icons are 144x144 and fill the frame edge-to-edge. Shrink them so they
// read as a small top-aligned icon rather than covering the whole button.
const ICON_SIZE_PX = 96

/** "Slot Take First_Key Icon.png" -> "ICON_SLOT_TAKE_FIRST" */
function constNameFor(filename) {
	const base = filename.replace(/_Key Icon\.png$/i, '').replace(/\.png$/i, '')
	const slug = base
		.toUpperCase()
		.replace(/[^A-Z0-9]+/g, '_')
		.replace(/^_+|_+$/g, '')
	return `ICON_${slug}`
}

const filenames = readdirSync(iconsDir)
	.filter((f) => f.toLowerCase().endsWith('.png'))
	.sort()

const lines = [
	'/**',
	' * Base64-encoded Stream Deck preset icons.',
	' * Generated by scripts/generate-icons.mjs from every PNG in icons/ - do not edit by hand.',
	' * Run `yarn icons` after adding/removing/changing files in icons/.',
	' */',
	'',
]

const scratchDir = mkdtempSync(path.join(tmpdir(), 'overlaysuno-icons-'))

const seen = new Set()
try {
	for (const filename of filenames) {
		const constName = constNameFor(filename)
		if (seen.has(constName)) {
			throw new Error(`Duplicate icon constant name "${constName}" derived from "${filename}"`)
		}
		seen.add(constName)

		const resizedPath = path.join(scratchDir, filename)
		execFileSync('sips', ['-Z', String(ICON_SIZE_PX), path.join(iconsDir, filename), '--out', resizedPath], {
			stdio: 'ignore',
		})

		const data = readFileSync(resizedPath).toString('base64')
		lines.push(`export const ${constName} = 'data:image/png;base64,${data}'`)
	}
} finally {
	rmSync(scratchDir, { recursive: true, force: true })
}

writeFileSync(outFile, lines.join('\n') + '\n')
console.log(`Wrote ${filenames.length} icon(s) to ${path.relative(rootDir, outFile)}`)
